steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose#v2.1.0:
        build: probot-app-workflow
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ":jest:"
    command: "yarn test"
    concurrency_group: "deploy"
    plugins:
      docker-compose#v2.1.0:
        run: probot-app-workflow
    agents:
      queue: workers
  - wait
  - name: ":rocket:"
    command: "scripts/deploy.sh"
    concurrency: 1
    concurrency_group: "deploy"
    branches: master
    plugins:
      docker-compose#v2.1.0:
        run: probot-app-workflow
    agents:
      queue: workers

